## JEEBase (OpenLiberty Version) 

CDI, JPA (EclispLink), JSF (+custom component taglib), Omnifaces, JAX-RS, EJB-lite, Deltaspike, SecurityAPI, Javascript, CSS.

- Os recursos necessários( 'jdbc/jeebaseDS' e 'mail/jeebaseMailSession' ) estão configurados no https://github.com/luisfga/jeebase/blob/openliberty/src/main/liberty/config/server.xml[server.xml],
usado pelo plugin para executar o servidor e a aplicação.
- É necessário configurar o plugin com a sua instalação do Open Liberty, alterando o pom.xml

    e.g., <installDirectory>/home/luisfga/openliberty-21.0.0.4</installDirectory>

- É necessário configurar as seguintes variáveis de ambiente:
    para o banco: DB_HOST, DB_PORT, DB_USER, DB_PASS, JEEBASE_DATABASE, 
    para a sessão de email: MAIL_HOST, MAIL_PORT, MAIL_USERNAME e MAIL_PASSWORD

- https://github.com/luisfga/jeebase/blob/openliberty/Dockerfile[Dockerfile]


Para gerar um jar e executá-lo
----
mvn clean package liberty:package -Dinclude=runnable
java -jar target/jeebase.jar
----

Passando argumentos pro jar
----
java -jar tager/jeebase.jar --variavel=valor
----

https://github.com/luisfga/jeebase/tree/wildfly[Branch da versão pro WildFly 23]

https://github.com/luisfga/jeebase/tree/tomee[Branch da versão pro TomEE 8.0.6]

https://github.com/luisfga/jeebase/tree/payara4[Branch da versão pro Payara 4.1.2.x] #JEE7
